---
- name: Symlink /usr/bin/python -> /usr/bin/python3
  hosts: all
  
  tasks:
    - name: Symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python;
        fi
      become: true

    - debug: var=ansible_host